name: QA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: info
          scandir: "./scripts"
        env:
          SHELLCHECK_OPTS: -e SC1091
