name: QA Terraform

on:
  push:
    paths-ignore:
      - "scripts/**"
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "scripts/**"
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TFLINT_VERSION: v0.56.0

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Security scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          trivy-config: trivy.yaml
          ignore-unfixed: false
          scan-ref: terraform/

  compliance-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          skip_check: CKV_GIT_4,CKV_SECRET_6,CKV_GCP_125
          quiet: true
          framework: terraform

  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: terraform-linters/setup-tflint@v5
        name: Setting up TFLint
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}
      - name: Initializing TFLint
        run: tflint --init
      - name: Linting
        run: tflint --chdir=terraform/ --recursive -f compact --disable-rule=terraform_module_pinned_source

  validate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        name: Setting up Terraform
      - name: Format check
        run: terraform fmt -check -recursive terraform/
      - name: Init (no backend)
        run: terraform -chdir=terraform/ init -backend=false
      - name: Validate
        run: terraform -chdir=terraform/ validate -no-color
