name: QA Terraform

on:
  push:
    paths-ignore:
      - "scripts/**"
    branches: ["main"]
    tags-ignore: ["**"]
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Security scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          trivy-config: trivy.yaml
          ignore-unfixed: false
          scan-ref: terraform/

  compliance-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          skip_check: CKV_GIT_4,CKV_SECRET_6,CKV_GCP_125
          quiet: true
          framework: terraform

  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        name: Setting up TFLint
        with:
          tflint_version: v0.56.0
      - name: Initializing TFLint
        run: tflint --init
      - name: Linting
        run: tflint --chdir=terraform/--recursive -f compact --disable-rule=terraform_module_pinned_source
