name: QA

on:
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
          scandir: "./scripts"
